import type { Metadata } from "next";
import "@/styles/style.css";
import "@/styles/fonts.css";
import "@/styles/web.css";
import "@/styles/ui.css";
import "@/styles/line-awesome-1.3.0/css/line-awesome.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
