CREATE TABLE `articles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `caption` int(11) DEFAULT NULL,
  `content` text NOT NULL,
  `created_at` datetime NOT NULL,
  `created_by` int(11) NOT NULL,
  `modified_at` datetime NOT NULL,
  `modified_by` int(11) NOT NULL,
  `reading` int(11) NOT NULL DEFAULT 0,
  `likes` int(11) NOT NULL DEFAULT 0,
  `dislikes` int(11) NOT NULL DEFAULT 0,
  `category` int(11) NOT NULL,
  `branch` int(11) NOT NULL,
  `post_on` datetime NOT NULL,
  `resume` text NOT NULL,
  `theme` varchar(255) NOT NULL,
  `duration` int(11) NOT NULL,
  `slug` text NOT NULL,
  `stats` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_pic_caption` (`caption`),
  KEY `fk_man_creator` (`created_by`),
  KEY `fk_man_editor` (`modified_by`),
  KEY `fk_cat_art` (`category`),
  KEY `fk_branch_art` (`branch`),
  CONSTRAINT `fk_branch_art` FOREIGN KEY (`branch`) REFERENCES `branch` (`id`),
  CONSTRAINT `fk_cat_art` FOREIGN KEY (`category`) REFERENCES `category` (`id`),
  CONSTRAINT `fk_man_creator` FOREIGN KEY (`created_by`) REFERENCES `manager` (`id`),
  CONSTRAINT `fk_man_editor` FOREIGN KEY (`modified_by`) REFERENCES `manager` (`id`),
  CONSTRAINT `fk_pic_caption` FOREIGN KEY (`caption`) REFERENCES `pictures` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
insert into `articles` (`branch`, `caption`, `category`, `content`, `created_at`, `created_by`, `dislikes`, `duration`, `id`, `likes`, `modified_at`, `modified_by`, `post_on`, `reading`, `resume`, `slug`, `stats`, `theme`, `title`) values (1, 4, 3, '<figure class=\"image\"><img src=\"/assets/captions/artimg6.jpg\"></figure><p>Entre l\'art et le personnage, lequel est vraiment digne d\'être le critère de l\'artiste. C\'est cette question que nous allons voir ensemble aujourd\'hui.</p>', '2026-04-05 11:43:20', 2, 0, 12, 3, 0, '2026-04-05 11:43:20', 2, '2026-04-05 11:43:20', 1, 'Entre l\'art et le personnage, lequel est vraiment digne d\'être le critère de l\'artiste.', 'cest-quoi-etre-artiste', NULL, 'Questionnement, tendance', 'C\'est quoi etre artiste ?');
insert into `articles` (`branch`, `caption`, `category`, `content`, `created_at`, `created_by`, `dislikes`, `duration`, `id`, `likes`, `modified_at`, `modified_by`, `post_on`, `reading`, `resume`, `slug`, `stats`, `theme`, `title`) values (1, 3, 1, '<figure class=\"image\"><img src=\"/assets/captions/artimg8.jpg\"></figure><p>Le schema de la gloire. Juste pour un exemple.</p>', '2026-04-05 12:08:03', 2, 0, 9, 4, 0, '2026-04-05 12:08:03', 2, '2026-04-05 12:08:03', 12, 'Le schema de la gloire', 'le-schema-de-la-gloire', NULL, 'Musique', 'Le schema de la gloire');
insert into `articles` (`branch`, `caption`, `category`, `content`, `created_at`, `created_by`, `dislikes`, `duration`, `id`, `likes`, `modified_at`, `modified_by`, `post_on`, `reading`, `resume`, `slug`, `stats`, `theme`, `title`) values (1, 2, 1, '<figure class=\"image\"><img src=\"/assets/captions/artimg9.jpg\"></figure><p>Joe a livré une performance exceptionnelle entre l\'euphorie et la classe.</p>', '2026-04-05 14:23:34', 2, 0, 5, 5, 0, '2026-04-05 14:23:34', 2, '2026-04-05 14:23:34', 34, 'Joe a livré une performance exceptionnelle entre l\'euphorie et la classe.', 'la-performance-musicale-de-joe', NULL, 'Live,Musique', 'La performance musicale de Joe !');
