CREATE TABLE `punchlines` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `presentation` int(11) NOT NULL,
  `picture` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `artist` varchar(255) NOT NULL,
  `lyrics` text DEFAULT NULL,
  `punchline` text NOT NULL,
  `year` int(11) NOT NULL,
  `category` int(11) NOT NULL,
  `comment` text DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `created_by` int(11) NOT NULL,
  `modified_at` datetime DEFAULT NULL,
  `modified_by` int(11) NOT NULL,
  `post_on` datetime DEFAULT NULL,
  `branch` int(11) NOT NULL,
  `stats` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_base_pic` (`presentation`),
  KEY `fk_final_pic` (`picture`),
  KEY `fk_cat_punch` (`category`),
  KEY `fk_man_punch_creator` (`created_by`),
  KEY `fk_man_punch_editor` (`modified_by`),
  KEY `fk_branch_punch` (`branch`),
  CONSTRAINT `fk_base_pic` FOREIGN KEY (`presentation`) REFERENCES `pictures` (`id`),
  CONSTRAINT `fk_branch_punch` FOREIGN KEY (`branch`) REFERENCES `branch` (`id`),
  CONSTRAINT `fk_cat_punch` FOREIGN KEY (`category`) REFERENCES `category` (`id`),
  CONSTRAINT `fk_final_pic` FOREIGN KEY (`picture`) REFERENCES `pictures` (`id`),
  CONSTRAINT `fk_man_punch_creator` FOREIGN KEY (`created_by`) REFERENCES `manager` (`id`),
  CONSTRAINT `fk_man_punch_editor` FOREIGN KEY (`modified_by`) REFERENCES `manager` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;insert into `punchlines` (`artist`, `branch`, `category`, `comment`, `created_at`, `created_by`, `id`, `lyrics`, `modified_at`, `modified_by`, `picture`, `post_on`, `presentation`, `punchline`, `stats`, `title`, `year`) values ('Fouiny', 1, 4, NULL, '2026-04-03 20:18:13', 1, 1, NULL, '2026-04-03 20:18:13', 1, 1, '2026-04-03 20:18:13', 2, 'L\'argent n\'a pas d\'odeur, mais Lafouine a du flaire', 2, 'Hello', 2026);
